apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo-backend
  namespace: otel-demo
  labels:
    app: otel-demo-backend
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-demo-backend
  template:
    metadata:
      labels:
        app: otel-demo-backend
        component: backend
    spec:
      containers:
      - name: backend
        image: djhope99/otel-demo-backend:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LLM_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: otel-demo-config
              key: LLM_PROVIDER
        - name: BEDROCK_MODEL_ID
          valueFrom:
            configMapKeyRef:
              name: otel-demo-config
              key: BEDROCK_MODEL_ID
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: otel-demo-secrets
              key: AWS_ACCESS_KEY_ID
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: otel-demo-secrets
              key: AWS_SECRET_ACCESS_KEY
              optional: true
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: otel-demo-secrets
              key: AWS_REGION
              optional: true
        - name: OTEL_COLLECTOR_URL
          valueFrom:
            secretKeyRef:
              name: otel-demo-secrets
              key: OTEL_COLLECTOR_URL
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000 
