apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-demo-config
  namespace: otel-demo
data:
  # LLM Provider configuration
  LLM_PROVIDER: "bedrock"
  OPENAI_MODEL: "o3"
  BEDROCK_MODEL_ID: "us.anthropic.claude-sonnet-4-20250514-v1:0"
  
  # Application configuration
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "http://localhost:3000,https://your-domain.com"
  
  # Backend configuration
  BACKEND_PORT: "8000"
  BACKEND_HOST: "0.0.0.0" 