apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-demo-config
  namespace: otel-demo
data:
  # LLM Provider configuration
  LLM_PROVIDER: "openai"
  OPENAI_MODEL: "gpt-4o-mini"
  BEDROCK_MODEL_ID: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  
  # Application configuration
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "http://localhost:3000,https://your-domain.com"
  
  # Backend configuration
  BACKEND_PORT: "8000"
  BACKEND_HOST: "0.0.0.0" 