apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- secret.yaml
- configmap.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml

# Common labels for all resources
commonLabels:
  app: otel-demo-generator
  version: v1.0.0

# Namespace for all resources
namespace: otel-demo

# Images to use - updated to use djhope99 Docker Hub registry
images:
- name: otel-demo-backend
  newName: djhope99/otel-demo-backend
  newTag: latest
- name: otel-demo-frontend
  newName: djhope99/otel-demo-frontend
  newTag: latest 