apiVersion: v1
kind: Secret
metadata:
  name: otel-demo-secrets
  namespace: otel-demo
type: Opaque
stringData:
  # OpenAI configuration
  OPENAI_API_KEY: "your-openai-api-key-here"
  
  # AWS Bedrock configuration (if using Bedrock)
  AWS_ACCESS_KEY_ID: "your-aws-access-key-here"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key-here"
  AWS_REGION: "us-east-1"
  
  # Optional: Custom OTLP endpoint
  OTEL_COLLECTOR_URL: "http://localhost:4318" 